# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: Flutter Tutorial

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- script: ls
  displayName: 'list contents'


- task: FlutterInstall@0
  inputs:
    channel: 'stable'
    version: 'latest'

- task: FlutterBuild@0
  inputs:
    target: 'ios'
    projectDirectory: '.'
    iosCodesign: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/build/ios/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Release .app to staging directory'

# - task: CmdLine@2
#   inputs:
#     script: 'cd build/ios/ && ls && sudo cp -r ./iphoneos $Build.artifactstagingdirectory'
#     workingDirectory: '$(Build.SourcesDirectory)'
#   displayName: 'check contents of build dir with .app exts'

- task: CmdLine@2
  inputs:
    script: 'ls'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  displayName: 'contents of staging dir'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ipa-drop'
    publishLocation: 'Container'