# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: Flutter Tutorial

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- script: ls
  displayName: 'list contents'


- task: FlutterInstall@0
  inputs:
    channel: 'stable'
    version: 'latest'

- task: FlutterBuild@0
  inputs:
    target: 'ios'
    projectDirectory: '.'
    iosCodesign: false

- task: CmdLine@2
  inputs:
    script: 'pwd'

- task: CmdLine@2
  inputs:
    script: 'sudo cp -r build/ios/iphoneos/Runner.app  $Build.ArtifactStagingDirectory'
    #workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'copy using bash'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'build/ios/iphoneos/Runner.app'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Release .app to staging directory'

- task: CmdLine@2
  inputs:
    script: 'cd build/ios/iphoneos && ls && cp -r ./Runner.app $Build.artifactstagingdirectory'
    workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'check contents of build dir with .app exts'

- task: CmdLine@2
  inputs:
    script: 'ls'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'
  displayName: 'contents of staging dir'


- task: CmdLine@2
  inputs:
    script: 'cd build/ios/iphoneos && ls && cp -r ./Runner $Build.artifactstagingdirectory'
    workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'check contents of build dir without .app exts'

# - task: CmdLine@2
#   inputs:
#     script: 'mv app-release.apk ''$(PROJECT-NAME).apk'''
#     workingDirectory: '$(build.artifactstagingdirectory)'
#   displayName: 'Rename apk to project name apk'

# - task: CmdLine@2
#   inputs:
#     script: 'ls'
#     workingDirectory: '$(build.artifactstagingdirectory)'
#   displayName: 'List contents'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ipa-drop'
    publishLocation: 'Container'